sudo : required 

Services:
- Docker 

Before-install :
- docker build -t parthiveer/docker-react -f Dockerfile.dev .

script:

- docker run -e CI=true parthiveer/docker-react npm run test

language : generic